### PR TITLE
WIP: Fix travis CI

### PR DESCRIPTION
**Pull request by romansavrulin**

### CODE REVIEW

**Comment by xnk** [comment]
Travis already builds properly again using only the -y flag ut seems, see this build for example: https://travis-ci.org/UnifiedEngineering/T-962-improvements/builds/337281948

**Comment by romansavrulin** [comment]
@xnk , ok, Thank you! Didn't mentioned this.

Do you plan to make a new release soon?

**Comment by xnk** [comment]
Literally as we speak

**Comment by romansavrulin** [comment]
@xnk, Good news! We are ready to test build in a couple of days, because we are about to add 4-thermocouples fix But it seems like deploy of HEX to github is broken for new build.

**Comment by xnk** [comment]
Yeah, something must have broken with the oauth token. I'll generate a new one and test again

**Comment by xnk** [comment]
Successful deploy from Travis-CI, but the binary grew significantly with the new compiler.

**Pull request closed without merging**
