### PR TITLE
Downloaded the schematic from dropbox to make sure it stays available

### PR DESCRIPTION
**Pull request by jieter**
Adding the schematic to the repo.

refs #69

### CODE REVIEW

**Comment by wulfmans** [comment]
does that mean i can remove the link from my dropbox ?

**Comment by jieter** [comment]
Yes. 

Bud do you maybe have a high res version?

**Comment by wulfmans** [comment]
I can make a high res PDF or supply the orcad design files

**Comment by jieter** [comment]
On 08-10-15 16:36, wulfmans wrote:
> I can make a high res PDF or supply the orcad design files
>

PDF would be great.

-- 
Gerardus de Haenstraat 22
2612 JJ Delft
06-42901018
jieter@jieter.nl

**Comment by wulfmans** [comment]
here you go
if you notice any mistakes please let me know

**Comment by jieter** [comment]
If you tried attaching the pdf to your email reply to github: that doesn't work yet. Please provide a link so I can download it...

**Comment by wulfmans** [comment]
send me a gmail addy and i can direct mail it

**Comment by jieter** [comment]
jieter@gmail.com

**Comment by jieter** [comment]
removed the png and added the pdf. Just sent @wulfmans an email asking for a version with everything on one page, cause it's not that readable now.

**Comment by jieter** [comment]
@xnk This is now updated with a nice PDF version. Ready to be merged.

**Comment by bankrasrg** [comment]
I have compared the schematic of @wulfmans with the board from my T962A and found a number of differences. Pin 58 of the LPC2134 should be labeled "P0.23". The pin numbering of some of the connectors is reversed. The PNP emitter follower is not connected to pin 56 of the LPC2134, but actually implements a debounce function for the S-key. And red LED D6 should have its anode to 3.3 V. That should cover most of the changes. I have created my own schematic in EagleCAD, which can be downloaded here: http://www.bankras.org/projects/wp-content/uploads/2016/03/T962A_schematic.pdf. I have tried to use the component names from the silk screen of my board and have added the improvements. Feel free to use it to update the Orcad schematic or to add it to the repository.

**Comment by jieter** [comment]
@bankrasrg your schematics look very nice, I updated this PR with your version.

@xnk any chance we can get this merged?

**Comment by jieter** [comment]
@xnk ping?

**Comment by GitLang** [comment]
Mr bankrasrg , your schematic is very good and nice high resolution. I noticed a couple of possible errors that I commented on Hackaday, as follows ...

"I think there is an error in the PDF schematic from the wiki, entitled T962A REV 0.1, 3/7/16 8:52PM. It involves the HEAT and COOL lines, I think they are back to front, and the pin numbers are shifted by 1. I’ll try to explain.

The flashing wiki explains about the fan and heat coming on during ISP and to put a weak pullup on P0.8 and P0.9. According to the LPC2134 datasheet, P0.8 is pin 33 and P0.9 is pin 34. If I trace my PCB, I can see U9 pin 1 tracked to the CPU pin 34 and U9 pin 3 is tracked to pin 33. This contradicts the pin 32 and 33 shown on the schematic. Also, I think that makes the labeling of HEAT and COOL reversed. 

Schematic also shows U9-10 (buffered P0.8) driving the Fan triac through R8 and the Heater SSR through the Heater socket. U9-12 (buffered P0.9) only seems to drive the unpopulated U2 triac and the LED. As a cross check, my PCB seems to be tracked as follows :

P0.8 : U13-33 to U9-3, U9-4 to U9-11, U9-10 to R8 and…
P0.9 : U13-34 to U9-1, U9-2 to U9-13, U9-12 to R6 and…
"

**Comment by bankrasrg** [comment]
Thanks a lot, GitLang. You are absolutely right. I will correct this in schematic rev 0.2.

**Comment by jieter** [comment]
@xnk Just pushed an update from @bankrasrg

**Comment by KLEYNOD** [comment]
Hi 
Wonder where I can download the latest schmatic.  Try to make cadence version and new pcb once for all to  make option to have more channels on TC sensor and independent triac control.

**Pull request merged**
