### PR TITLE
Serial command

### PR DESCRIPTION
**Pull request by jieter**
Not ready yet, but getting useful:
2015-02-04-101657-pid_control_test
2015-02-04-102551-amtech_syntech-lf

The log is currently saved as plot to png/pdf and CSV.

This serial control I build is not really the way to go, I guess making some commands which work globally is more useful. Something like:

```
select profile <id>\n
bake <setpoint>\n
set <setting> <value>\n
```

Any thoughts?

### CODE REVIEW

**Comment by jieter** [comment]
Just added global serial commands...

**Comment by jieter** [comment]
When running `./serial-control.py test`, the python script should trigger all reflow profiles and write a log/images to `logs/`.

**Comment by xnk** [comment]
Really nice!! I'll go through this and see what the results will be with my oven!

**Comment by jieter** [comment]
This is the current list of commands:
```
 bake <setpoint>       Enter Bake mode with setpoint
 help                  Display help tex
 list profiles         List available reflow profiles
 quiet                 No logging in standby mode
 reflow                Start reflow with selected profile
 settings              List current settings
 setting <id> <value>  Set setting id to value
 select profile <id>   Select reflow profile by id
 stop                  Exit reflow or bake mode
```
Only `setting <id> <value>` is not really implemented yet...

**Comment by jieter** [comment]
Just added code to implement `setting <id> <value>`. Nothing fancy yet, it only takes the int which is stored in NV, It would be more intuitive to allow input in the values of the setting (properly scaled).

To reduce code duplication, I added `setup.(c|h)` to factor out the setup related stuff.

**Comment by jieter** [comment]
@xnk any thoughts or things I need to fix?

**Comment by jieter** [comment]
Just found (and fixed) a bug in the setup display on the machine, `sizeof(buf)` is not the same in the function in `setup.c`, so passed an extra argument to `Setup_snprintFormattedValue()`.

**Comment by xnk** [comment]
Hmm, seems like RAMPTEST and PIDTEST got enabled by default now. I don't think anyone will mistake them for "real" profiles though, so no big issue!

**Comment by jieter** [comment]
yes, would be nice to have them always available from the serial interface (for running the tests), but they might be hidden from the profile selection on the oven interface...

**Pull request merged**
