### PR TITLE
Added a target to download & compile lpc21isp utility.

### PR DESCRIPTION
**Pull request by jieter**
Automated building of the `lpc21isp` tool from https://github.com/Senseg/lpc21isp

### CODE REVIEW

**Comment by jieter** [comment]
Hmm, just tested with this source for the , it doesn't work. 
```
...
Erasing sector 0 first, to invalidate checksum. OK 
Sector 1: .......................Error on writing block_CRC (1)
Non-zero download reasult: 4103.  Exiting.
```
Will update this with the original source from sourceforge...

**Comment by jieter** [comment]
This works like charm now.

**Comment by jieter** [comment]
This  should be it. Rebased and squashed into one commit.

**Comment by xnk** [comment]
Awesome, looks good! Thanks!!

**Pull request merged**
