### PR TITLE
Adding bake timer functionality

### PR DESCRIPTION
**Pull request by jieter**
Here is some work on timer functionality. I'm not completely satisfied yet, but it works. Can also be triggered with a serial command `bake 100 3600` will bake for an hour after reaching 100 degrees.

Please share your thoughts on how I implemented it and possible improvements.

Issues: 
 - [ ] if the temperature is just slightly above the setpoint, the timer is started, but if the temperature drops below the setpoint, the timer stops ticking. We need some hysteresis here.
 - [ ] Add a short beep after setpoint is reached.
 - [x] Fix beep after timer reached zero.
 - [x] Some extra reordering of the bake LCD layout might be in order.
 - [x] Display time in mm:ss
 - [ ] Time might also need (hh:)mm:ss formatting, ignoring the seconds if time is greater than an hour.
 - [x] Save bake setpoint in NV storage (first part of #50)

### CODE REVIEW

**Comment by xnk** [comment]
Looks like a really good start! X1 and X2 readout seems to be broken though, I will check how it looks with my oven.

**Comment by jieter** [comment]
I think Cold-Junction temperature will interfere with the stop button, since I now increase `y` only if X1/X2 exists...

**Comment by jieter** [comment]
I just pushed a big refactoring of the code in `reflow.c`, moved quite some code it to `sensors.c` and `reflow_profiles.c`. This makes it much more clear what's going on in `reflow.c`, without all the different TC-interface specifics. Makes fixing the items of the list above much more straightforward.

**Comment by jieter** [comment]
Just pushed some LCD reordering and saving of setpoint to nvram.

Updated Bake LCD:


X1 and X2 fit in there now.

**Comment by jieter** [comment]
@xnk did you have an opportunity to test this? Anything blocking this? I'll continue to work on the open issues, but it might be good to merge these first?

**Comment by jieter** [comment]
@xnk still alive?

**Comment by xnk** [comment]
Yes, still here @jieter , sorry for the outage! I have been crazy busy and to make things worse I managed to hurt my neck quite bad beginning of February. That severely slowed progress. I'm back now and everything's fine. I have added the I2C-to-SPI bridge board too so I now have three different ways to measure thermocouples in this oven.

**Comment by jieter** [comment]
Never mind, glad you're fine!

**Comment by xnk** [comment]
Pulling in the pull request locally and testing right now!

**Comment by xnk** [comment]
Merged! Bake timer works and I tested debug and about serial commands as well. Quiet mode got changed to be default on it seems?

**Comment by jieter** [comment]
Oh, yeah, quiet moed. Those are the things I forget to change back, sorry.

**Comment by xnk** [comment]
Quiet works for me, the temperature logging always runs when reflowing, that's the important part!

My merge commit of this pull request seems to be a bit strange, it doesn't list the individual commits it consists of. I had to manually merge it as the float stuff had changed in main, but that's it, everything else was merged automatically.

**Comment by jieter** [comment]
Yeah, I should have done a rebase after the set-serial merge I guess.

**Pull request closed without merging**
