### PR TITLE
System Fan Temperature Adjustment

### PR DESCRIPTION
**Pull request by DeathBeforeDecaf**
Hi Werner,

Thank you very much for making a great implementation of the T962 firmware!  My name is Anton Walters and I purchased the reflow oven after reading Colin's article in Circuit Cellar.  So far I've implemented the hacks (removed masking tape, added ground wire, Cold-Junction sensor, added your improved firmware, PWM System Fan Control).  Additionally I've added a second 40mm fan on the opposite side to push air across the thermocouple circuit board and it seems to keep the cold junction about 5degC above the min system fan temperature value.

I've also created a branch of your firmware that allows a user to adjust the temperature where the system fan spins up and attempts to cool down the circuit board.  The branch lets a user update the system fan temperature value from the setup screen.  If you have time please check it out and let me know if the changes seem reasonable.

If other projects don't get in the way I may attempt to add a toaster oven convection fan and create a very small breakout board for a SSR controller that would plug in to the serial programmer connection.  From my review of the design that's just about the last PWM output that's still easily available.

Anyways - thanks again for the updated firmware!

-Anton
Seattle, WA

### CODE REVIEW

**Comment by jieter** [comment]
@xnk this looks good too, didn't test it on the actual machine though.

**Comment by GitLang** [comment]
Werner, Look close at your PCB. I noticed mine has tracks for a third output named "Plate" as in hotplate. I think it may be for multiple use of the board, maybe for driving a convection element jst as you are proposing. There is also an unpopulated tinned copper area on the board, I think for another triac and another MC.. opto triac.

**Comment by xnk** [comment]
Hmm, interesting!! I was fairly sure that nothing else was traced out on my board but will have to take another look when I have the oven opened next time!

I need to go through all my email regarding this project, I see that there’s been quite some activity here while I’ve been occupied with other day-job activities! I haven’t disappeared, this just hasn’t been highest priority.

/wj

**Comment by GitLang** [comment]
You can see it clearly on the right. Maybe the extra triac and associated circuitry is used in place of the T962A'a SSR on the T962. I haven't seen a T962 to compare it with. As you see the unpopulated socket on the board edge clearly says Plate.

plate

**Comment by xnk** [comment]
Very interesting! That’s where my heaters are connected (with the heatsink TRIAC, U8 populated).. I never saw the silkscreen there as the connector was covering it…

/wj

**Comment by dtwaddell** [comment]
@DeathBeforeDecaf , I was thinking of adding a second 40mm fan as exhaust as well, and going with two quieter ones.  Did you pay attention to what CFM and decibels you used for your fans?  I'm worried that going with a quieter fan will not be enough air volume.  The quietest fans (<20 dB) are only 4 CFM, while louder fans (35-40 dB) are 12 CFM.

**Comment by GitLang** [comment]
Decaf - why don't you just try the latest firmware from here?. As long as you have done the cold junction mod, it will only bring the fan one when needed. In my case it has only actually come on ONCE. It just doesn't get that warm in there. Can't get any quieter than a fan that's not on :)

**Comment by DeathBeforeDecaf** [comment]
@dtwaddell  I've purchased a second 40mm fan but have not yet added it to the circuit.  The critical consideration is the clearance (fan thickness), since there isn't realy much room.  A regular thickness 1U fan is too large for this application.  I have also purchased an oven convection motor to place a radial fan within the oven to stir the air around.  Unfortunately I haven't had time to install either but will try to get back to this project early next year.

**Comment by DeathBeforeDecaf** [comment]
Hi Werner that sounds like a great plan - I need to check out the newest firmware anyways.

Thanks!

**Pull request closed without merging**
