### PR TITLE
Try to add some more structure to the readme and add links to the wiki

### PR DESCRIPTION
**Pull request by jieter**
Let's discuss possible documentation improvements, as things are getting duplicated between the wiki and `README.md`. Here is a start for `README.md` and some updates to `COMPILING.md`

### CODE REVIEW

**Comment by jieter** [comment]
Will also add a note about system fan control which is currently only documented in the source.

**Comment by jieter** [comment]
I tried to add this image to [this wiki page](https://github.com/UnifiedEngineering/T-962-improvements/wiki/System-fan-control), but I'm not allowed to :(

system-fan-control-mod

**Comment by xnk** [comment]
Nice image!

Hmm, isn’t github supposed to upload images automatically to githubusercontent.com <http://githubusercontent.com/> and then link to it from there? It seems that has worked previously for waldo. I can see how this works, I’m new to how GitHub operates their wikis!

/wj

**Comment by xnk** [comment]
I linked the image from the system-fan page. Awesome page by the way, thanks for documenting!

Is the controller board for a T-962 or a T-962A? I notice the absence of the heater TRIAC other than that it looks exactly like my T-962 controller.

**Comment by jieter** [comment]
T-962A. There is a separate solid state relay in on the backplate of the oven.

**Comment by xnk** [comment]
Makes sense, heater is higher power.

I'm very interested in seeing how both the RAMPTEST and PIDTEST profiles 
execute in a T-962A oven, so if you have some spare time it would be 
great if you could log the UART output when running them. The reason why 
I'm interested is that I would like to see how much the ramp speed 
differs between the smaller and larger oven. This will in turn indicate 
if PID tuning has to be different between the two or not.

Also I've heard that the reflow fan in 962A doesn't quite behave the 
same way as the 962 one. Does your fan run slowly at min fan speed 8 or 
did you have to increase min speed for it to turn?

**Comment by jieter** [comment]
I guess you'll have to wait for the spare part to arrive, for it will be a challange to select the right profile without an LCD.
The fan seems to work just fine, will check it later.

I noted the measurements of the thermocouples were a little off compared to a thermocouple I put on a PCB in de drawer connected to my multimeter. The temperature in the PCB was at 240, while the internal temperature read about 5 degrees lower.


(picture taken through the drawer window)

Also note the locations of the thermocouples are not left/right but front/back.

**Comment by xnk** [comment]
Right! Let's see if I have a few spare cycles to implement some commands/responses over the serial port in the meantime. 

Does your DMM readout go down after a few minutes at that temperature? I noticed that the original TC's seemed to be take a relatively long time to respond to high temps as some of the heat seemed to be shunted away from the junction. That will result in an oven temperature above the setpoint that will then go down with no _reported_ change in temperature. That's a really odd measurement error, I get slightly different readouts with different DMM TCs as well so I had a total of 6 TCs in the oven when calibrating (two DMMs, my spare two channels of the TC interface and then my actual two oven TCs). 

It's worth noting that the air temperature (that the oven regulates) will not necessarily match the PCB temperature. Are you getting a very different readout with the DMM TC measuring the air temperature? In the end you want the PCB to be the correct temperature though, especially around the peak reflow temperature, so the gain and offset calibration might have to be tweaked. Are both of your oven TCs reporting similar values? 

I need to think about how to deal with front/back in bake and setup mode (the two user facing places the channels are referred to as L and R). Do you remember which channel was front and which one was back in your oven?


Sent from my Sony Xperia™ smartphone

---- Jan Pieter Waagmeester wrote ----

**Pull request merged**
